### ISSUE TITLE
Shows back on RN 0.46 Android

### ISSUE THREAD

**Issue by bcifu** [plmok61/react-native-flip-component#2]
HI,

I am using RN 0.46 due to some performance issues and am trying to use this component.  The issue is that on Android the front side of the component is never shown.  It shows the back side reflected over the y-axis when the front should be showing.  Then when the card flips it flips to show the back side the right way around.  Is there anything I can do to fix this.

**Comment by plmok61** [comment]
Yep it looks like backface visibility still doesn't work on Android. The PR is still open https://github.com/facebook/react-native/pull/15970

I'll see if I can come up with a work around

**Comment by saifkamaal** [comment]
Any updates to this? I can still see this issue on RN 0.57, platform android.

![screenshot_1546597273](https://user-images.githubusercontent.com/29369768/50683599-0a5d4180-102c-11e9-840e-464e523709ff.png)

**Comment by plmok61** [comment]
This should be fixed now
